version: "3"

services:
  micro_agent_v2:
    build: .
    container_name: micro_agent_v2
    ports:
      - "8010:8010"
      - "8000:8000"
      - "2222:22"
    volumes:
      - ./workspace/data:/app/workspace/data
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: unless-stopped
